config/routes.rb
Rails.application.routes.draw do

  # CRUD para crear Races
  resources :tracks

  # Configurando el Index
  root 'tracks#index'

  # Vista de los mapas
  match 'maps/maps_view/:id' => 'maps#maps_view', :as => :maps_maps_view, via: [:get]

  # Creando y borrando  Markers
  match 'maps/create' => 'maps#create', :as => :maps, via: [:post]
  match 'maps/destroy/:id' => 'maps#destroy', :as => :maps_destroy, via: [:get]





end

app/models/datum.rb
class Datum < ActiveRecord::Base
    belongs_to :track
    has_many :marks

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  #belongs_to :datum
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
    has_many :data
    has_many :marks
    has_attached_file :gpx
    do_not_validate_attachment_file_type :gpx

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_track_id


  def maps_view
    # Tomando variables

    @id = params[:id]

    # Cargando data para la vista map_view

    @data = Datum.where(track_id: @id)
    @center = Datum.where(track_id: @id).last

    # cargando datos para los markers
    @markers = Mark.where(track_id: @id)

  end

  def create
    # Tomando variables
    @lat = params[:latlng][:latitude]
    @lon = params[:latlng][:longitude]
    @track_id = params[:latlng][:track_id]

    # logueando para hacer un checkpoint
    logger.info " ##################################  Creando Marker  #{@lat} #{@lon} #{@track_id}"

    @mark_create = Mark.create([{lat: @lat, lon: @lon, track_id: @track_id}])

    # redirigiendo para maps_view
    redirect_to maps_maps_view_path(@track_id)

  end

  def destroy
    track_id = params[:track_id]
    Mark.destroy(params[:id])
 ### redirigiendo de vuelta al mapa
    redirect_to maps_maps_view_path(track_id)
  end


  def dist_params
    params.require(:latlng).permit(:latitude[], :longitude[])
  end
  def set_track_id
      @track = params[:id]
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def create
    logger.info " ###################################{params[:lat]}"
    @mark = Mark.new params[mark_params]

    if @mark.save

      redirect_to maps_maps_view_path(1)
      #render :json => { }
    else
    render :json => { }, :status => 500
    end
  end

  def mark_params
    params.require(:mark).permit(:track_id, :label, :lat, :lon)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]


  def index
    @tracks = Track.all
  end


  def show
  end


  def new
    @track = Track.new
  end


  def edit
  end


  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        ### Tomando el ultimo registro guardado
        f = Track.last
        ### Tomando el ID
        trackid = f.id
        ### path del archivo gpx
        path = f.gpx.path
        ### Abriendo archivo gpx
        doc = Nokogiri::XML(File.open(path))
        ### sacando <name> y guardando
        name = doc.xpath('//xmlns:name/text()').map{|pt| pt.to_s}
        f.update(track: name)

        ### tomando lon, lat, ele y time
        x = doc.xpath('//xmlns:trkpt/@lon').map{|pt| pt.to_s.to_f}
        y = doc.xpath('//xmlns:trkpt/@lat').map{|pt| pt.to_s.to_f}
        e = doc.xpath('//xmlns:ele/text()').map{|pt| pt.to_s.to_f}
        t = doc.xpath('//xmlns:time/text()').map{|pt| pt.to_s}

        ### grabando en Datum
        $i = 0
        $num = x.count

        while $i < $num  do
          Datum.create([{track_id: trackid, lon: x[$i], lat: y[$i], ele: e[$i], time: t[$i]}])
          $i +=1
        end
        ### Obteniendo/registrando inicio/fin de carrera
        time_begin = Datum.where(track_id: f.id).first
        time_end = Datum.where(track_id: f.id).last
        ### obteniendo la diferencia de tiempo
        ### validando formato extraño de gpx
        if time_end.time.blank?
          logger.info "Archivo no tiene recurrencia de fecha"
        else
          time_elapsed = TimeDifference.between(time_begin.time, time_end.time).humanize
        end
        ### su registro loco en el log
        logger.info "time_begin: #{time_begin.time} time_end: #{time_end.time} #{time_elapsed} "
        ### guardando datos
        f.update(time_begin: time_begin.time, time_end: time_end.time, time_elapsed: time_elapsed)




        format.html { redirect_to @track, notice: 'Carrera creada satisfactoriamente.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Carrera creada satisfactoriamente.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Carrera creada satisfactoriamente.' }
    end
  end



  private
    def set_track
      @track = Track.find(params[:id])
    end


    def track_params
      params.require(:track).permit(:track, :gpx, :gpx_content_type, :gpx_file_size, :gpx_updated_at, :time_begin, :time_end, :time_elapsed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
  <script src='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.css' rel='stylesheet' />

  <!-- Comentando GL JS -->
<!--  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css' rel='stylesheet' /> -->
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--#5685C4-->
        <%= link_to "Welcu - Trails", root_path , class: "navbar-brand white" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/maps/maps_view.html.erb
<style type='text/css'>
html,
body,
#map {
  width: 800px;
  height: 340px;
  position: relative;


}

</style>
<div style="width:100%; height:350px; position:relative; margin-top:90px;">
  <div id='map'></div>
</div>
<div style="width:100%; height:300px; position:relative;">
  <%= area_chart @data.group(:time).maximum(:ele), discrete: true%>
</div>
<div>
  <input class="get-markers" type="button" value="Get all the Markers" />
</div>
<script>

// Iniciando el Mapa

  L.mapbox.accessToken = 'pk.eyJ1Ijoibm9yZWxsYW5hIiwiYSI6ImNpbzR5emozNDAxcHJ2aWx6OHRoNHVzMWMifQ.NMjJ_fsTMlCCkzytqaV0LQ';

  var map = L.mapbox.map('map', 'mapbox.outdoors')
      .setView([<%=@center.lat%>, <%=@center.lon%>], 15);


// dibujando con polyline

  var line_points = [
  <%@data.each do |d|%>
    [<%=d.lat%>, <%=d.lon%>],
  <%end%>
];

  var polyline_options = {
    color: '#000'
};
// cargando polyline en el mapa
  var polyline = L.polyline(line_points).addTo(map);


// poniendo los markers ya creados
  <%@markers.each do |m|%>
    var db_marker = L.marker([<%=m.lat%>, <%=m.lon%>,]).addTo(map);

// para borrar markers
    db_marker.bindPopup('<%= link_to "Borrar", maps_destroy_path(:id => m.id, :track_id => m.track_id )%>');
  <%end%>

// Atachando en el map con el evento click
  map.on('click', onMapClick);

// Creando nuevos markers
  function onMapClick(e) {
    var geojsonFeature = {
      "type": "Feature",
      "properties": {},
      "geometry": {
      "type": "Point",
      "coordinates": [e.latlng.lat, e.latlng.lng]
    }

  }

//creando variables para mandar el post
  var latitude = e.latlng.lat;
  var longitude = e.latlng.lng;
  var track_id = <%=@id%>

// post para enviar markers al create
  $.ajax({
          url : "/maps/create",
          type : "post",
          data : { latlng: {latitude, longitude, track_id} }
      });

  var marker;

  L.geoJson(geojsonFeature, {

    pointToLayer: function(feature, latlng) {

      marker = L.marker(e.latlng, {

        title: "Resource Location",
        alt: "Resource Location",
        riseOnHover: true,
        draggable: false,

      });

      marker.on("popupopen", onPopupOpen);


      return marker;
    }
  }).addTo(map);
}

// para remover los makers
  function onPopupOpen() {

    var tempMarker = this;

    $(".marker-delete-button:visible").click(function() {
    map.removeLayer(tempMarker);
  });
}


</script>

app/views/tracks/_form.html.erb
<%= form_for @track, :html => { :class => "form-horizontal track" } do |f| %>

  <% if @track.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :gpx_file_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :gpx, :class => 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tracks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tracks/edit.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/index.html.erb
<%- model_class = Track -%>

<div class="page-header">
  <h1>Race</h1>
</div>

  <div class="row">
    <% @tracks.each do |track| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <!--<img src="..." alt="...">-->
          <div class="caption">
            <h3><%=track.track%></h3>
            <p><%= track.time_elapsed %></p>
            <p>File Name: <%= track.gpx_file_name %></p>
            <p>Created At: <%= track.created_at %></p>

            <%= link_to "See More", maps_maps_view_path(:id => track.id), class:"btn btn-welcu" %>

            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        track_path(track),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
                        :class => "btn btn-danger" %>
          </div>
        </div>
      </div>
      <!--<script>
        var patron='[&quot;';
        var patron_2= '&quot;]';
        var cadena= "<%=track.track%>";
        cadena.replace(patron,'');
        cadena.replace(patron_2,'');
      </script>-->
    <% end %>
  </div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_track_path,
            :class => 'btn btn-welcu' %>

app/views/tracks/new.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tracks/show.html.erb
<%- model_class = Track -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:track) %>:</strong></dt>
  <dd><%= @track.track %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_name) %>:</strong></dt>
  <dd><%= @track.gpx_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_content_type) %>:</strong></dt>
  <dd><%= @track.gpx_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_file_size) %>:</strong></dt>
  <dd><%= @track.gpx_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gpx_updated_at) %>:</strong></dt>
  <dd><%= @track.gpx_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tracks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_track_path(@track), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              track_path(@track),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>